language: php

php:
- 5.5
- 5.4
- 5.3

services:
- rabbitmq

before_script:
- pear channel-discover pear.phix-project.org
- pear -D auto_discover=1 install -Ba phix/phix4componentdev
- phpenv rehash
- phpenv config-add .rabbit.ini
- phing build-vendor
- wget -O rabbitmqadmin 'http://guest:guest@localhost:55672/cli/rabbitmqadmin'
- python rabbitmqadmin -q import .rabbit.config

script: phing code-review

